services:
  articles-site:
    image: ghcr.io/zhuyidian/yidian-articles:main
    pull_policy: always
    container_name: yidianhub-articles
    restart: unless-stopped
    networks:
      caddy_frontend:
        aliases:
          - yidianhub-articles

networks:
  caddy_frontend:
    external: true
    name: yidian-api_frontend
