worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;

  server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /_astro/ {
      expires 1y;
      add_header Cache-Control "public, immutable";
      try_files $uri =404;
    }

    location / {
      try_files $uri $uri/ $uri/index.html =404;
    }
  }
}
